### ISSUE TITLE
composer update failed to v3.40

### ISSUE THREAD

**Issue by nucreativa** [vlucas/phpdotenv#359]
Hi, i try to composer update my laravel app, and i get this issue
```
Updating vlucas/phpdotenv (v3.3.3 => v3.4.0): Loading from cache    Failed to execute unzip -qq  '/Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/vlucas/phpdotenv/e5b6ed41efa8748d01157c4a3fe078cf' -d '/Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/composer/19329fc5'

[/Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/vlucas/phpdotenv/e5b6ed41efa8748d01157c4a3fe078cf]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/vlucas/phpdotenv/e5b6ed41efa8748d01157c4a3fe078cf or
        /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/vlucas/phpdotenv/e5b6ed41efa8748d01157c4a3fe078cf.zip, and cannot find /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/vlucas/phpdotenv/e5b6ed41efa8748d01157c4a3fe078cf.ZIP, period.

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
```

this make in the end
```
PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/laravel/framework/src/Illuminate/Container/Container.php:790
Stack trace:
#0 /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/laravel/framework/src/Illuminate/Container/Container.php(790): ReflectionClass->__construct('config')
#1 /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build('config')
#2 /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\Container\Container->resolve('config', Array)
#3 /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\Container\Container->make('config', Array)
#4 /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/laravel/framework/src/Illuminate/Container/Container.php(1225): Ill in /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 790

Fatal error: Uncaught ReflectionException: Class config does not exist in /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/laravel/framework/src/Illuminate/Container/Container.php:790
Stack trace:
#0 /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/laravel/framework/src/Illuminate/Container/Container.php(790): ReflectionClass->__construct('config')
#1 /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build('config')
#2 /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\Container\Container->resolve('config', Array)
#3 /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\Container\Container->make('config', Array)
#4 /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/laravel/framework/src/Illuminate/Container/Container.php(1225): Ill in /Users/arywibowo/Sites/laravel-enterprise-app-setup/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 790
```

and when i downgrade to v3.3.0, its working fine.

**Comment by nucreativa** [comment]
i'm sorry, it seems the problem on my local machine, composer issue. i'm close this
